### ISSUE TITLE
Horizontal Server List

### ISSUE THREAD

**Issue by SakethKanchi** [Dyzean/Tokyo-Night#12]
Can you add support for horizontal server list. The user ID thing becomes a mess if I enable it.

![image](https://user-images.githubusercontent.com/70198692/152105899-f070f14c-be0a-4ba0-9c49-8ad4bc58c29c.png)

![image](https://user-images.githubusercontent.com/70198692/152105934-e4a1dd26-4fd5-4d5f-ba88-d59e94e42cf8.png)

And when we hover on it

![image](https://user-images.githubusercontent.com/70198692/152105992-079b3adf-fb94-4941-af58-a9dbae432beb.png)

**Comment by Dyzean** [comment]
On v2 you can disable the "VSCode like User Area" by commenting the import url

**Comment by SakethKanchi** [comment]
> On v2 you can disable the "VSCode like User Area" by commenting the import url [`main`/tokyo-night.theme.css#L30](https://github.com/Dyzean/Tokyo-Night/blob/main/tokyo-night.theme.css?rgh-link-date=2022-02-02T06%3A45%3A07Z#L30)

It works thanks a lot. And is there any chance of you implementing Popout models from Simplify to Tokyo Night?

**Comment by Dyzean** [comment]
> > On v2 you can disable the "VSCode like User Area" by commenting the import url [`main`/tokyo-night.theme.css#L30](https://github.com/Dyzean/Tokyo-Night/blob/main/tokyo-night.theme.css?rgh-link-date=2022-02-02T06%3A45%3A07Z#L30)
> 
> It works thanks a lot. And is there any chance of you implementing Popout models from Simplify to Tokyo Night? Or anyway to change the colorscheme to Simplify to Tokyo Night

Nope, but i might create a "unique" popout for this theme

**Comment by SakethKanchi** [comment]
> > > On v2 you can disable the "VSCode like User Area" by commenting the import url [`main`/tokyo-night.theme.css#L30](https://github.com/Dyzean/Tokyo-Night/blob/main/tokyo-night.theme.css?rgh-link-date=2022-02-02T06%3A53%3A08Z#L30)
> > 
> > 
> > It works thanks a lot. And is there any chance of you implementing Popout models from Simplify to Tokyo Night? Or anyway to change the colorscheme to Simplify to Tokyo Night
> 
> Nope, but i might create a "unique" popout for this theme

Thanks a lot.
