### ISSUE TITLE
Discord broke the theme again

### ISSUE THREAD

**Issue by KotonBads** [Dyzean/Tokyo-Night#14]
Friends list, user list when mentioning someone, vscode user area, compact mode, username background, and syntax highlighting

![image](https://user-images.githubusercontent.com/66117568/158730233-4c495baa-51e5-40c5-a16c-bc35de830759.png)

**Comment by Dyzean** [comment]
can i know what discord channel do you use (stable/canary/ptb)? also please provide fullscreen screenshot

**Comment by KotonBads** [comment]
I use discord flatpak so that should be the stable branch, also somehow it's fixed? Everything's themed properly again
![image](https://user-images.githubusercontent.com/66117568/158939405-ab40b6ff-5dec-4738-952e-6a1be39b0af7.png)

**Comment by Dyzean** [comment]
thats weird, might be the theme/discord not loaded properly.
