### ISSUE TITLE
Folder Colors 

### ISSUE THREAD

**Issue by keefeeilish** [Dyzean/Tokyo-Night#16]
Is there a way to get back the colors of the folders? I understand that you must have changed it for a reason, but I believe the folder colors will make Tokyo Night look better
![image](https://user-images.githubusercontent.com/78688659/161367757-a7ce3705-4699-42d5-ab9c-6c06f710b936.png)
![image](https://user-images.githubusercontent.com/78688659/161367768-4b423f30-ed92-47cd-87e5-5e2d5f306b49.png)
If you could even just tell me how to do get the colors on my own end, that'd be great too!

**Comment by Dyzean** [comment]
Should be fixed on 7aa8d16
