### ISSUE TITLE
Clicking servers on initial launch causes the selection menu to collapse and expand without processing the request

### ISSUE THREAD

**Issue by JuniorSuperTux** [Dyzean/Tokyo-Night#17]
The following is the strange behavior

https://user-images.githubusercontent.com/65844719/170972382-e3f5b247-9404-433a-93a2-6d5f21b1480b.mp4

**Comment by Dyzean** [comment]
looks like discord's issue tbh, custom css doesn't have anything to do with such behaviour.

**Comment by JuniorSuperTux** [comment]
Perhaps it's' BetterDiscord's issue? Because that doesn't seem to happen when I'm using the default theme
