### ISSUE TITLE
weird strip on a fullscreen stream

### ISSUE THREAD

**Issue by offlxnz** [Dyzean/Tokyo-Night#18]
![Screenshot_1](https://user-images.githubusercontent.com/107271606/173117488-2df385ed-e5d0-4c6e-b64a-9df6f7a54c7a.png)
i'm using white theme and idk why did it appreared, but without theme always is good

**Comment by Dyzean** [comment]
looks like discord broke it again, im p sure we have that issue while back ago. i might fix it later, im busy with exam atm

**Comment by Dyzean** [comment]
seems like discord changing something again, its fixed now i'll close this issue.
![image](https://github.com/Dyzean/Tokyo-Night/assets/69681505/96a4fdc3-f163-4ad3-91b5-08f9455fa32b)
