### ISSUE TITLE
Fullscreen Issue

### ISSUE THREAD

**Issue by 3obz** [Dyzean/Tokyo-Night#2]
Hello,
Thank you so much for the great work as this in a matter of a day turned to be probably my favorite theme, if there's only one thing I can change about it it would be that big line on the right when you're on youtube together and having discord on full screen mode *and yes this does exist in dark and light themes*.

![image](https://user-images.githubusercontent.com/86505125/129472023-584730ee-6b49-4cdb-9a40-67a8c3008b42.png)

**Comment by ExtraviNull** [comment]
This will also happen if you join a discord stream and Fullscreen it.

**Comment by Dyzean** [comment]
sorry for the issue you're getting, i'll try to fix that rq

**Comment by Dyzean** [comment]
sadly its kinda hard to fix, the issue is cause by this line 
https://github.com/Dyzean/Tokyo-Night/blob/0d267f6acc774f02d6d56753b4b0f322deaefde6/main.css#L404-L406

removing `max-width` will fix that thick bar issue, but it'll broke discord with small resolution

**Comment by ExtraviNull** [comment]
Thank you.

**Comment by Dyzean** [comment]
fixed 👍
