### ISSUE TITLE
Stylus support?

### ISSUE THREAD

**Issue by Lassebq** [Dyzean/Tokyo-Night#25]

**Comment by Dyzean** [comment]
no plan for that, sorry. iirc discord webapp have different css classes. if someone willing to do it its fine tho 😁

**Comment by Lassebq** [comment]
No, apparently it does work with stylus, you just need to add some metadata in the comment such as name, author and etc, and make the file end with ".user.css". then opening a raw.githubusercontent.com link should open said style in stylus

**Comment by Lassebq** [comment]
https://github.com/orblazer/discord-nordic/blob/master/nordic.user.css

**Comment by Lassebq** [comment]
Yeah, it works.
