### ISSUE TITLE
Top bar a few pixels off

### ISSUE THREAD

**Issue by Tryflle** [Dyzean/Tokyo-Night#27]
At least on Vencord, I've noticed that the top bar is a few pixels off and it's really bothering me.
![image](https://github.com/Dyzean/Tokyo-Night/assets/111710533/388cd9ca-d34b-4a33-8c02-f0f80c6eb31c)
![image](https://github.com/Dyzean/Tokyo-Night/assets/111710533/c2c638e7-a1ab-48e3-990b-27a65f4808cf)
This has been happening for a while and I was hoping it could be fixed as once you notice it it's impossible to unsee.
I know this theme isn't updated often anymore but I really love this theme and I hate to see it slowly being broken overtime. Hoping that you can fix it. 

BTW: Could just be a me problem, but the only theme I'm using is this one. I can't get any friends to test and confirm that this is the case for them as well because none of them have the energy to ADD THE THEME.. bruh.

**Comment by Dyzean** [comment]
fixed on commit d02bb36
