### ISSUE TITLE
Emojis, gifs and gift are gone

### ISSUE THREAD

**Issue by Tryflle** [Dyzean/Tokyo-Night#28]
![image](https://github.com/Dyzean/Tokyo-Night/assets/111710533/276dda0a-9c4c-4805-bb3b-ffc29f8cedca)
they breakin everything man
i love this theme
2 bug reports in 2 days
again hope you can fix it sometime, but if not, that's fine. i get that it's not maintained anymore.

**Comment by Dyzean** [comment]
fixed on commit d02bb36
