### ISSUE TITLE
Theme doesnt work after major discord update

### ISSUE THREAD

**Issue by AlfredKhachatryan** [Dyzean/Tokyo-Night#29]
I try to fix it by myself through class fixer https://syndishanx.github.io/Website/Update_Classes.html but it doesnt help

**Comment by Tryflle** [comment]
if you still need this, using the main.css from my fork seems to work. i opened a pr and im waiting on something to happen with it. for now you could try adding https://raw.githubusercontent.com/Tryflle/Tokyo-Night-Fix/main/main.css for your theme instead, it works perfectly for me.

**Comment by Dyzean** [comment]
already fixed on commit d02bb36 👍🏼
