### ISSUE TITLE
Spotify Modal Issue

### ISSUE THREAD

**Issue by strwbzzy** [Dyzean/Tokyo-Night#4]
Hello,
Thank you for your hard work and I appreciate your time spent on this theme, but it seems like Powercord's Spotify Modal is causing an overlay issue with the theme.

![image](https://user-images.githubusercontent.com/30149567/129995637-a4173bfd-5bfe-449a-95d5-e157686194c9.png)

**Comment by Dyzean** [comment]
fixed 👍
