### ISSUE TITLE
Spotify Modal Issue #2

### ISSUE THREAD

**Issue by strwbzzy** [Dyzean/Tokyo-Night#5]
Hello,
I appreciate your quick response to the previous issue, but it shouldn't be looking like this. 
![image](https://user-images.githubusercontent.com/30149567/130050397-9ef66c7e-e784-4560-aed0-216c7727352e.png)
Thank you, once again.

**Comment by Dyzean** [comment]
sadly i don't have spotify premium so i can't check what classes that control button use 😔

**Comment by strwbzzy** [comment]
I didn't know that, well, maybe we should keep this so that others can help us solve this

**Comment by Dyzean** [comment]
i just buy spotify premium, i'll try to fix it rq

**Comment by Dyzean** [comment]
fixed 👍

**Comment by strwbzzy** [comment]
Thank you for your update.
