### ISSUE TITLE
Theme Rewrite

### ISSUE THREAD

**Issue by Dyzean** [Dyzean/Tokyo-Night#6]
I'm planning to rewrite this theme completely, this theme code is shit tbh.
I'll start rewriting this theme after exams this week and finish it as soon as possible.

**Comment by Dyzean** [comment]
The plan i currently have is write the theme in scss then compile it to css for BetterDiscord support. 👍

**Comment by Wolfhound905** [comment]
While you are at is, could you as Tokyo Night Light?

**Comment by Dyzean** [comment]
> While you are at it, could you as Tokyo Night Storm? 

I already created that? Just turn on Light Mode on your discord

**Comment by Dyzean** [comment]
Ahhh... Yea im planning for making Tokyo Night Strom ColorScheme tho.

**Comment by Wolfhound905** [comment]
ya sorry, it was late and I edited a few times. Ya thanks if you gonna add it. and just to be clear here is a pic of what I'm talking about
![image](https://user-images.githubusercontent.com/58155937/135289994-89d42889-4a3a-4835-9f6c-f2a7d7388e0b.png)

**Comment by xmdbro** [comment]
> Ahhh... Yea im planning for making Tokyo Night Strom ColorScheme tho.

Any update on this? I prefer storm over default tokyo night and would love to have it on discord.
