### ISSUE TITLE
Discord/DB update broke bottom left panel area

### ISSUE THREAD

**Issue by Willy-JL** [Dyzean/Tokyo-Night#8]
Yesterday night BD prompted for an update and ever since then my bottom left panel area has been broken...
![image](https://user-images.githubusercontent.com/49810075/139870236-92b82db4-ceab-4cef-b81b-6620954c84ac.png)

**Comment by Dyzean** [comment]
weird, it works fine for me

**Comment by Willy-JL** [comment]
I tried reinstalling the theme (through the ThemeRepo plugin) but still nothing

**Comment by Willy-JL** [comment]
I'm on Linux if that matters

**Comment by Dyzean** [comment]
im on linux tho 🤔 that probably some plugins issue

**Comment by Dyzean** [comment]
i see... 🤔
