### ISSUE TITLE
Online friend list

### ISSUE THREAD

**Issue by BennetLe** [Dyzean/Tokyo-Night#9]
The counter next to online friends is incorrect and showing that the same number as total friends on discord.

**Comment by Dyzean** [comment]
What? Can you explain more with screenshot? That seems not theme issue

**Comment by BennetLe** [comment]
I previously used a theme  where you could not see the counter, and so I forgot that I had it installed. It is not a problem of your theme. Thank you for the reply anyway, and sorry that I bothered you for nothing.
